### ISSUE TITLE
Allow adding a parameter/input/output description

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#103]
We need to know what the inputs mean, and users need to provide a simple description in their model configurations. Otherwise they will not be usable. They can skip it, of course, but we should have the possibility to capture this in the mic configuration with a `description` tag. This does not need to be part of the wizard, just a warning and documentation is enough.

**Comment by Cmheidelberg** [comment]
pr #102 creates a description field in the inputs/ params/ outputs of the mic.yaml.

Example of `mic.yaml` after step2 now 
```yaml
inputs:
  inpittwo_in:
    path: data\inpitTwo.in
    description: ''  # insert description left of this comment
  input1_in:
    path: data\input1.in
    description: ''  # insert description left of this comment
parameters:
  parameter1:
    default_value: 0  # value added by MIC. Replace with your own default value
    description: ''  # insert description left of this comment
  parameter2:
    default_value: 0  # value added by MIC. Replace with your own default value
    description: ''  # insert description left of this comment
  parameter3:
    default_value: 0  # value added by MIC. Replace with your own default value
    description: ''  # insert description left of this comment
step: 4
configs:
- data\input1.in
```


I forgot to add a warning message for the user to write their descriptions. I will add it my next push.
