### ISSUE TITLE
Step 6 does not recognize outputs

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#143]
**Describe the bug**
After executing step6, mic does not recognize the outputs correctly. Instead it only recognize as output a config file used as input.
I am running version `mic v0.4.4`

**To Reproduce**
I have a simple component that generates a folder and a zip file with the contents of that folder. My mic.yaml file is as follows (before execution):
```
inputs:
  config_yml:
    path: data/config.yml
    description: ''  # insert description left of this comment
parameters:
  exclude:
    default_value: Subsidy  # value added by MIC. Replace with your own default value
    description: A veryyyyyyyyyyyyyyyyyyyyy looooooooooooooooooooooong descripttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttion  # insert description left of this comment
step: 6
configs:
- data/config.yml
```
mic.yaml after execution:
```
inputs:
  config_yml:
    path: data/config.yml
    description: ''  # insert description left of this comment
parameters:
  exclude:
    default_value: Subsidy  # value added by MIC. Replace with your own default value
    description: A veryyyyyyyyyyyyyyyyyyyyy looooooooooooooooooooooong descripttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttion  # insert description left of this comment
step: 6
configs:
- data/config.yml
outputs:
  config_yml:
    path: config.yml
    description: ''  # insert description left of this comment
last_execution_dir: /nas/home/dgarijo/testMIC/export_test_0.4.4/executions/06_08_21_33_49/src
```
The execution is successful:
```
(env) [dgarijo@node1 export_test_0.4.4]$ mic encapsulate step6
Downloading the base image and building your image
Adding inputs
The execution directory is available /nas/home/dgarijo/testMIC/export_test_0.4.4/executions/06_08_21_33_49/src
Running
 ./run   -i1 config.yml  -p1 Subsidy
Run complete
The model has generated the following files:
   config.yml
Added: config_yml as a output
Success
(env) [dgarijo@node1 export_test_0.4.4]$ cd executions/06_08_21_33_49/src
(env) [dgarijo@node1 src]$ ls
catalog_export  catalog_export.zip  config.yml  export_mc.py  io.sh  output.sh  run
```
`catalog_export.zip` is the file that should be the output from my model. `config.yml` is both an input and a config file.

**Expected behavior**
I was expecting `catalog_export.zip` to be captured as an output instead of `config.yml`.

**Desktop (please complete the following information):**
 - Unix (node1.mint.isi.edu)

I attach my full model component.
[export_test_0.4.4.zip](https://github.com/mintproject/mic/files/4750008/export_test_0.4.4.zip)
