### ISSUE TITLE
[mic v1] - step2 Exposing a file inside a directory

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#148]
**Is your feature request related to a problem? Please describe.**

If the input is a directory, we are going to compress the directory into a zip file to create one input.
However, a user can want to expose a file in the directory.

For example, the topoflow model configuration has two inputs

We have one an input is a zip file:

aggregated-inputs | Topoflow aggregated inputs for the Awash region

![image](https://user-images.githubusercontent.com/2365990/84208007-8b153e00-aa67-11ea-8cf0-991c804f81f3.png)

The second input is the precipitation rate and we must copy the precipitation rates inside the previous directory.

**Describe the solution you'd like**

**WARNING**: If the user compress a directory, the future inputs must have the same name. A message in the description can be a good place to add a warning

```yaml
inputs:
         aggregated-inputs:
                  path: region/
                  description: "This is a zip file, the zip file must have a directory with the name `region`"
         precipation:
                 path: region/climate.rts
```

Then,

The run wrapper must be:

```
cp climate.rts region
#run topoflow
```

**Describe alternatives you've considered**

**Additional context**
