### ISSUE TITLE
Ease how parameters are declared

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#160]
At the moment we need to declare the parameters in the yaml file and in the config files of the model, plus also set the config files that are being used.

This is too complex. Instead, I propose the following:

- Users will only have to declare parameters in their config files, e.g., ${param_name}
- MIC will scan all files in the docker image to recognize `${something_goes_here}` in them (initially we can also assume users will tell us the config files.
- MIC will extract param names and add them to the mic.yaml file automatically.

This way users don't need to add parameters manually.

**Comment by Cmheidelberg** [comment]
@dgarijo 
Since I dont know if config files will be standardized to list which values are the user's parameters mic config is looking for any variable enclosed in `${}`. There is also no way to know the default value for the parameter based on how the flags are currently set up (since the flag replaces the value)

Example:
```json
chris@chris-ubuntu20:/home/chris/Desktop/tests/simpleModel  (master)$ cat config.json 
{
"input" :
  {
  "dataset_name" : "${config_json}"
},
"output" :
  {
  "path" : "./"
},
"params" :
  {
  "a" : "${a}",
  "b" : "${b}",
  "c" : "${c}"
  }
}
```

```yaml
chris@chris-ubuntu20:/home/chris/Desktop/tests/simpleModel  (master)$ cat mic/mic.yaml 
step: 2
name: csa
chris@chris-ubuntu20:/home/chris/Desktop/tests/simpleModel  (master)$ mic encapsulate configs config.json -f mic/mic.yaml 
Added: /home/chris/Desktop/tests/simpleModel/config.json as a configuration file
chris@chris-ubuntu20:/home/chris/Desktop/tests/simpleModel  (master)$ cat mic/mic.yaml 
step: 2
name: csa
configs:
  config_json:
    path: config.json
    format: json
parameters:
  config_json:
    default_value: 0
  a:
    default_value: 0
  b:
    default_value: 0
  c:
    default_value: 0

```

I am open to any ideas on a better way to implement this. I am also adding a option to stop auto parameter detection with the configs command

**Comment by dgarijo** [comment]
For default value, it's not possible, I agree, unless we add a syntax like ${a}{default=1} (maybe in next version)

For recognizing inputs as parameters, if you have your inputs already declared in the mic file, then you know they will not be parameters and can be removed. So in your case, the mic file would look like: 

```yaml
step: 2
name: csa
chris@chris-ubuntu20:/home/chris/Desktop/tests/simpleModel  (master)$ mic encapsulate configs config.json -f mic/mic.yaml 
Added: /home/chris/Desktop/tests/simpleModel/config.json as a configuration file
chris@chris-ubuntu20:/home/chris/Desktop/tests/simpleModel  (master)$ cat mic/mic.yaml 
step: 2
name: csa
configs:
  config_json:
    path: config.json
    format: json
parameters:
  a:
    default_value: 0
  b:
    default_value: 0
  c:
    default_value: 0
```
We would need to issue a warning for users telling them to verify the default values, and that's fine
