### ISSUE TITLE
Inputs should be automatically in run.sh

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#203]
The mic inputs are declared in `mic.yaml` file, but the right variables are not reflected in the run.sh file. For example, see this mic file excerpt:
```
inputs:
  input_txt:
    path: input.txt
    format: txt
code_files:
  test_192-1_0-snapshot-jar-with-dependencies_jar:
    path: test_192-1.0-SNAPSHOT-jar-with-dependencies.jar
    format: jar
outputs:
  out_txt:
    path: out.txt
    format: txt
```
The run file is:
```
BASEDIR=$PWD
. $BASEDIR/io.sh 1 1 1 "$@"
CURDIR=`pwd`
## INPUTS VARIABLES
input_txt=${INPUTS1}
## PARAMETERS VARIABLES
strength=${PARAMS1}
set -xe
####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT
pushd .
java -jar test_192-1.0-SNAPSHOT-jar-with-dependencies.jar -i input.txt -p ${strength} -o out.txt
popd
set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh
```
(Note that the parameter `strength` I changed it by hand).
Instead, it should be:
```
java -jar test_192-1.0-SNAPSHOT-jar-with-dependencies.jar -i ${input_txt} -p ${strength} -o ${OUTPUTS1}
```
(or maybe not the outputs, since it doesn't matter in this case). But if we don't want users to edit this file, this should have been reflected automatically, or it won't work correctly
