### ISSUE TITLE
parameters should be automatically in run.sh

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mic#254]
The parameters part is missing

_Originally posted by @sirspock in https://github.com/mintproject/mic/issues/203#issuecomment-657736757_

**Comment by sirspock** [comment]
If the variable is a string. The result must be

```
./test.sh "${string_variable}

```

**Comment by Cmheidelberg** [comment]
How can we know how to map parameters to their mic.yaml values? If two parameters share the same value there is no way to automatically know which is which. (without some type of standardized way to declare parameters)
```yaml
.
.
.
parameters:
  start_year:
    default_value: 2015
    type: int
    description: start year
  base_altitude:
    default_value: 2015
    type: int
    description: starting altitude in meters
```
invocation:
`./my_script.py 2015 2015 input.csv`
current wrapper generated:
`./my_script.py 2015 2015 ${input_csv}`
wrapper we want:
`./my_script.py ${start_year} ${base_altitude} ${input_csv}`
or
`./my_script.py ${int_variable_1} ${int_variable_2} ${input_csv}`
