### ISSUE TITLE
files with hyphen in yaml causes issues with run

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#293]
**Describe the bug**
I have a directory `ATX-Lot_line/`. When mic detects this as an input it adds it to the yaml as:
```yaml
atx-lot_line_zip
    path: ATX-Lot_line.zip
    format: zip
```
for some reason the hyphen will cause the file not to be found when using `mic pkg run`.

Error (traced from io.sh)
```
line 80: atx-lot_line_zip=/home/chris/Desktop/tests/pick_prop_pyththreeseven/mic/executions/07_31_15_38_50/src/ATX-Lot_line.zip: No such file or directory
```

manually editing the input name in the yaml fixed the issue.
