### ISSUE TITLE
notebook is ignoring the output

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mic#336]
**Describe the bug**

The configuration published doesn't have the output.

CWL spec is ok

```yaml
...
outputs:
  output_file:
    outputBinding:
      glob: ECMWF_regridded.nc
    type: File
```
